### ISSUE TITLE
期待能恢复该功能：点击APP登录按钮后，小窗口页面自动定位到二维码的位置

### ISSUE THREAD

**Issue by amor33** [Huozzzy/Learning-Learner#1]
十分感谢更新维护！
以前小熊有个功能是点击登录之后页面自动滚动到二维码的位置，方便直接扫码，但不知什么原因该功能有段时间之后失效了，期待作者能恢复该功能！

**Comment by jcsun-00** [comment]
+1+1

**Comment by jcsun-00** [comment]
原理可以考虑解析登陆页面的html源码，提取二维码链接，显示在软件界面应该就可了
