### ISSUE TITLE
期待新功能：打开本地频道

### ISSUE THREAD

**Issue by jcsun-00** [Huozzzy/Learning-Learner#12]
App端积分规则里有一条`本地频道`，要求打开使用本地频道内功能，完成要求会奖励1分。
在网页端首页中`全国学习平台展播`部分有各地频道，可以考虑做一个链接列表，然后随机选取一个链接，再点进去那个频道的任意一篇文章就可以了。

以上是草率思路，希望大家可以一起完善

**Comment by ttglad** [comment]
> App端积分规则里有一条`本地频道`，要求打开使用本地频道内功能，完成要求会奖励1分。 在网页端首页中`全国学习平台展播`部分有各地频道，可以考虑做一个链接列表，然后随机选取一个链接，再点进去那个频道的任意一篇文章就可以了。
> 
> 以上是草率思路，希望大家可以一起完善
https://github.com/ttglad/learning
增加自动答题的不香么

**Comment by Huozzzy** [comment]
> > App端积分规则里有一条`本地频道`，要求打开使用本地频道内功能，完成要求会奖励1分。 在网页端首页中`全国学习平台展播`部分有各地频道，可以考虑做一个链接列表，然后随机选取一个链接，再点进去那个频道的任意一篇文章就可以了。
> > 以上是草率思路，希望大家可以一起完善
> > https://github.com/ttglad/learning
> > 增加自动答题的不香么

推广都推到我下面来了？恶不恶心？

**Comment by hanliren** [comment]
您好，您的浏览器是哪个，我现在谷歌安装上没法打开，请问这是什么原因呢

**Comment by jcsun-00** [comment]
> 您好，您的浏览器是哪个，我现在谷歌安装上没法打开，请问这是什么原因呢

我用的就是Chrome浏览器，方便的话你可以贴一下你的问题截图，这样我们能一块看一下

**Comment by hanliren** [comment]
![图片](https://user-images.githubusercontent.com/68997192/141398493-befb0ed0-9b7b-49b3-ab2e-6ad253e20945.png)
您看一下，是 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

**Comment by hanliren** [comment]
我试验了几个浏览器，就是打不开这个东西，不知道为什么，以前都是拖动安装插件，也没有这个问题的，现在就是没法用

**Comment by jcsun-00** [comment]
这个

> ![图片](https://user-images.githubusercontent.com/68997192/141398493-befb0ed0-9b7b-49b3-ab2e-6ad253e20945.png) 您看一下，是 该扩展程序未列在 Chrome 网上应用店中，并可能是在您不知情的情况下添加的。

这是有解决办法的，具体如下：
1. 下载crx文件；
2. 把crx文件后缀改为zip，然后解压缩zip文件；
3. 使用Chrome加载已解压的扩展，选择第2步中解压出来的文件夹

**Comment by wangscsgit** [comment]
试着在浏览器打开全国学习平台展播-任意一个频道-任意一篇文章，分数没有变化。。

**Comment by wangscsgit** [comment]
自己写了个每日答题，每周答题，专项答题的脚本，有需要的的么

**Comment by wangscsgit** [comment]
自己写了个每日答题，每周答题，专项答题的脚本，有需要的的么

**Comment by Huozzzy** [comment]
本地频道功能经过尝试，暂无电脑浏览器实现的可能。
