### ISSUE TITLE
每周答题不自动答题

### ISSUE THREAD

**Issue by Suzii233** [Huozzzy/Learning-Learner#24]
最近的每周答题不会自动答了，只能到40分

**Comment by Huozzzy** [comment]
去app里看看你的每周答题是不是都已经答完了

**Comment by Suzii233** [comment]
没有啊，这几天都是手动答的

**Comment by Suzii233** [comment]
> 去app里看看你的每周答题是不是都已经答完了
没有答完啊，到2020年3月的题，这几天都是手动答的

**Comment by Suzii233** [comment]
> > 去app里看看你的每周答题是不是都已经答完了
> > 没有答完啊，到2020年3月的题，这几天都是手动答的

我复现了一下，每周答题自动跳到第四页（2019年）的题，不会往前遍历，然后卡在这里了

**Comment by sssres** [comment]
> 

我的也是，跳到第四页不答题，等会儿就退出了
