### ISSUE TITLE
每周答题和专项答题没有题目的情况下，会在题目页面无限刷新

### ISSUE THREAD

**Issue by Wings168** [Huozzzy/Learning-Learner#28]
前端报错信息：
Uncaught TypeError: Cannot read properties of undefined (reading 'getAttribute')

上下文
https://pc.xuexi.cn/points/exam-paper-list.html
堆叠追踪
js/exampaper.js:17 (匿名函数)
if (li.getAttribute("aria-disabled") == "false") {

**Comment by iiHarry** [comment]
我也是这样，希望大佬赶紧更新
