### ISSUE TITLE
依然有报错导致做题界面无法继续运行

### ISSUE THREAD

**Issue by Wings168** [Huozzzy/Learning-Learner#29]
Uncaught TypeError: Cannot read properties of null (reading 'disabled')
上下文
https://pc.xuexi.cn/points/exam-paper-detail.html?id=526
堆叠追踪
js/exampractice.js:128 (匿名函数)

Uncaught TypeError: Cannot read properties of null (reading 'click')
上下文
https://pc.xuexi.cn/points/exam-paper-detail.html?id=526
堆叠追踪
js/exampractice.js:128 (匿名函数)

**Comment by Huozzzy** [comment]
chrome浏览器即使有报错也是可以正常运行的
